#!/bin/bash

# This script sets up an Amazon RDS instance for a PHP application

CREATE PARAMETER GROUP

SELECT MYSQL COMMUNITY ENGINE

SELECT MYSQL 8.0

TYPE : DB PARAMETER GROUP

# CREATE  DB SUBNET GROUP

ENTER THE NAME
ENTER THE DESCRIPTION
SELECT THE VPC
SELECT THE SUBNETS AND AVAILABILITY ZONES

# CREATE A DB INSTANCE
GOTO RDS > DB Instances > Create DB Instance
SELECT STANDARD CREATE
SELECT MYSQL  ENGINE VERSION8.0
TEMPLATES SELECT FREE TIER
GO SETTINGS AND GIVE INSTANCE IDENTIFIER NAME
USERNAME KEEP IT admin / KEEP DEFAULT SELF MANAGED PASSWORD
AUTO GENERATE PASSWORD
SELECT db.t4g.micro
STORAGE 20 GB AND STORAGE TYPE IS GENERAL PURPOSE SSD (gp3)
UNCHECK AUTO SCALING AT THE ADDITIONAL STORAGE CONFIGURATION
UNDER COMPUTER RESOURCE : KEEP DEFAULT AND  SELECT VPC
SELECT THE DB SUBNET GROUP CREATED ABOVE
SELECT PUBLIC ACCESS AS NO
SELECT VPC SECURITY GROUPS CREATED
NO AVAILABILITY ZONE
KEEP DEFAULT IN THE DATABASE PORT AND DATABASE OPTIONS
ADDITIONAL CONFIGURATION, ENTER DATABASE NAME
AND SELECT PARAMETER GROUP CREATED ABOVE
UNCHECK ENABLE AUTOMATIC BACKUP, THIS NOT REAL APP
ENCRYPTION KEEP DEFAULT
LOG EXPORT IN REAL TIME MAKE SURE AALL CHECKED
CREATE DATABASE 

SAVE THE PASSWORD OF THE DB ON THE SCREEN

7TV0yDuHA4kpIKqN0Yjj
admin

SECOND DATABASE FOR SMART_CARE_LIVE
admin
VX2Atm4FECN61WYrSUMN
