#!/bin/bash

# This script sets up an Amazon ELASTICACHE

CREATE PARAMATER GROUP
NAME, DESCRIPTION, ENGINE VERSION
MEMCACHED 1.6 AND CREATE

CREATE SUBNET GROUP
NAME, DESCRIPTION, VPC, SUBNETS AND AVAILABILITY ZONES ACCEPT DEFAULTS
AND CREATE

CREATE MEMCACHED CACHE
SELECT ENGINE MEMCACHED
 SELECT DESIGN YOUR OWN CACHE
 SELECT STANDARD CREATE
 SELECT AWS CLOUD FOR LOCATION  

CLUSTER INFO ADD NAME AND DESCRIPTION
SELECT ENGINE AND PORT 11211
SELECT PARAMETER GROUP CREATED ABOVE
SELECT SUBNET GROUP CREATED ABOVE
SELECT NODE TYPE cache.t4g.micro
SELECT NUMBER OF CACHE NODES 1
SELECT SUBNETS GROUP ON CHOOSE EXISTING
NO AVAILABLE ZONE
GO NEXT SELECT MANAGE AND SELECT SECURITY GROUP

MAINTENACE WINDOW
SELECT NO PREFERRED MAINTENANCE WINDOW
TOPIC FOR AMAZON SNS NOTIFICATION CAN BE DISABLE
CLICK NEXT AND REVIEW
CREATE
